{application,rng,
             [{description,"An OTP application"},
              {vsn,"rand_byte-0.1.0"},
              {registered,[]},
              {mod,{rng_app,[]}},
              {applications,[kernel,stdlib,crypto]},
              {env,[]},
              {modules,[rand_algorithm,rng_app,rng_generator,
                        rng_generator_sup,rng_sup,trace_helper]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
